### ISSUE TITLE
Add docker-compose and config files to App example 

### ISSUE THREAD

**Issue by mkizesov** [Aidbox/node-server-sdk#7]
I think it'd be very useful to add docker-compose file (with separate service for typescript application) and config/env file to the [App example folder](https://github.com/Aidbox/node-server-sdk/tree/main/example) so anyone could just clone this folder and start this example app without any configuring.

**Comment by octoalex** [comment]
@mkizesov v2 branch contains an example folder. I think it will be enough to just copy and use

**Comment by octoshikari** [comment]
Example contains example project which you can copy and use
